### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by anntzer** [scikit-sparse/scikit-sparse#15] opened 2016-02-08 20:20 UTC
scikits-sparse seem to be leaking memory at an alarming rate :-(  After some valgrind'ing, I think that the `*cholmod_dense` mallocated in `_view_dense` (and likewise for the `*_sparse` versions) never get deallocated, even though the comments suggest otherwise:
```
    # This returns a Python object which holds the reference count for the
    # dense matrix; you must ensure that you hold onto a reference to this
    # Python object for as long as you want to use the cholmod_dense*
```
but the return value is, in the dense case, a matrix that had been passed as input, and, in the sparse case, an `(indptr, indices, data)` triple, neither of which deallocate the malloc'ed memory upon being gc'ed.

**Comment by njsmith** [comment] 2016-02-08 21:36
Hi Antony,
I haven't used this code in years, and it sounds like you do... any objection to my just giving you write access to fix things? :-)

**Comment by anntzer** [comment] 2016-02-08 22:08
Heh, I guess I got what I asked for :-)

**Comment by njsmith** [comment] 2016-02-09 01:18
Well, I would love to make it work better, I just absolutely don't have the time, so :-) Gave you access, have fun :-)

**Comment by anntzer** [comment] 2016-02-09 10:38
Should be fixed by 88392d7.

Ping'ing all contributors, @jluttine @rainwoodman @jsalvatier @chiffa @pf4d @kforeman @pv @yurivict; please let me know if you have any patches you're interested in getting merged in before I bug @njsmith to make a 0.3 release.

**Comment by jluttine** [comment] 2016-02-09 10:40
I don't have any. Actually, I haven't used this package for a few years now, but maybe someday again. Great package anyway, and nice job @anntzer :+1:

**Comment by chiffa** [comment] 2016-02-09 14:14
@anntzer : do you have your own branch with this commit merged so that I can pull it and stress-test it with my application?

**Comment by anntzer** [comment] 2016-02-09 17:32
@chiffa Try the pre-0.3 branch.

**Comment by rainwoodman** [comment] 2016-02-09 17:45
Hi Antony,

I haven't used this package for a few years neither. But glancing through
the code, it is not so clear to me why a pool is necessary.

Could you add a few lines of comments in the code to explain the memory
management model?

Thanks for the work!

**Comment by anntzer** [comment] 2016-02-09 18:25
Indeed, there was a simpler solution: allocate the matrice structs on the stack.

In the previous solution I was basically too lazy to figure out what the required lifetimes of each object was, so I bound all of them to the Factor object (everything gets GC'd/free()'d when the Factor is GC'd).  But it seems that a tighter coupling is possible (which is basically what @njsmith used to do).

**Comment by rainwoodman** [comment] 2016-02-10 17:02
Thanks for the clarification. This is indeed quicker than figuring it all out. Nevertheless, some explanation in the code would avoid the "ends cut off" scenario (c.f. http://selfdefinedleadership.com/blog/?p=158 ) :)

**Comment by anntzer** [comment] 2016-02-11 04:22
I squashed out the memorypool out of the history, so now the relevant patch is fairly trivial (795e59954ff859c588f19bb8ee4b865c28462b2f).

**Comment by anntzer** [comment] 2016-02-19 16:31
@chiffa Did you have any chance to check I didn't completely break your code?

**Comment by chiffa** [comment] 2016-02-19 18:38
@anntzer : failing to pip-install it for now. Ubuntu 14.04, installed with Anaconda Python.
```
ccd@BSNO7397-Ubuntu:~$ pip install -U git+https://github.com/scikit-sparse/scikit-sparse.git@pre-0.3
Collecting git+https://github.com/scikit-sparse/scikit-sparse.git@pre-0.3
  Cloning https://github.com/scikit-sparse/scikit-sparse.git (to pre-0.3) to /tmp/pip-QCiLno-build
Requirement already up-to-date: numpy in ./anaconda2/lib/python2.7/site-packages (from scikit-sparse==0.2+dev)
Requirement already up-to-date: scipy in ./anaconda2/lib/python2.7/site-packages (from scikit-sparse==0.2+dev)
Installing collected packages: scikit-sparse
  Running setup.py install for scikit-sparse ... error
    Complete output from command /home/ccd/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-QCiLno-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-t_nk2E-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/sksparse
    copying sksparse/test_cholmod.py -> build/lib.linux-x86_64-2.7/sksparse
    copying sksparse/__init__.py -> build/lib.linux-x86_64-2.7/sksparse
    creating build/lib.linux-x86_64-2.7/sksparse/test_data
    copying sksparse/test_data/illc1850.mtx.gz -> build/lib.linux-x86_64-2.7/sksparse/test_data
    copying sksparse/test_data/illc1033.mtx.gz -> build/lib.linux-x86_64-2.7/sksparse/test_data
    copying sksparse/test_data/illc1850_rhs1.mtx.gz -> build/lib.linux-x86_64-2.7/sksparse/test_data
    copying sksparse/test_data/well1850.mtx.gz -> build/lib.linux-x86_64-2.7/sksparse/test_data
    copying sksparse/test_data/well1850_rhs1.mtx.gz -> build/lib.linux-x86_64-2.7/sksparse/test_data
    copying sksparse/test_data/well1033.mtx.gz -> build/lib.linux-x86_64-2.7/sksparse/test_data
    copying sksparse/test_data/illc1033_rhs1.mtx.gz -> build/lib.linux-x86_64-2.7/sksparse/test_data
    copying sksparse/test_data/well1033_rhs1.mtx.gz -> build/lib.linux-x86_64-2.7/sksparse/test_data
    running build_ext
    building 'sksparse.cholmod' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/sksparse
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include/suitesparse -I/home/ccd/anaconda2/include/python2.7 -c sksparse/cholmod.c -o build/temp.linux-x86_64-2.7/sksparse/cholmod.o
    sksparse/cholmod.c:259:31: fatal error: numpy/arrayobject.h: No such file or directory
     #include "numpy/arrayobject.h"
                                   ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/ccd/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-QCiLno-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-t_nk2E-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-QCiLno-build
```
This error does not appear on the 0.2 branch: 

```
 pip install -U git+https://github.com/scikit-sparse/scikit-sparse.git
Collecting git+https://github.com/scikit-sparse/scikit-sparse.git
  Cloning https://github.com/scikit-sparse/scikit-sparse.git to /tmp/pip-HRJvNO-build
Requirement already up-to-date: numpy in ./anaconda2/lib/python2.7/site-packages (from scikits.sparse==0.2+dev)
Requirement already up-to-date: scipy in ./anaconda2/lib/python2.7/site-packages (from scikits.sparse==0.2+dev)
Installing collected packages: scikits.sparse
  Found existing installation: scikits.sparse 0.2
    Uninstalling scikits.sparse-0.2:
      Successfully uninstalled scikits.sparse-0.2
  Running setup.py install for scikits.sparse ... done
Successfully installed scikits.sparse-0.2+dev
```

**Comment by anntzer** [comment] 2016-02-20 01:14
I messed up a bit with how the include path was passed to GCC... try again?  (Note: I rewrote the history so you'll need to reset --hard.)

**Comment by chiffa** [comment] 2016-02-20 01:22
I am using the pre-0.3 head right away, so it should be ok. I will try it out tomorrow once I get my hands on a memory-bound box/

**Comment by chiffa** [comment] 2016-02-20 22:56
Can you benchmark the CPU usage on large matrices (>10 000x10 000)? Right now the CPU usage pattern and time it takes to compute is significantly worse than the previous one. I am using a different machine and it is possible that the difference is due to the difference in the bus CPU/bus.

**Comment by anntzer** [comment] 2016-02-20 22:57
Do you have a test case?  Thanks.

**Comment by chiffa** [comment] 2016-02-20 22:58
Yes, but it will take a while to set-up.

**Comment by anntzer** [comment] 2016-02-20 22:58
No hurry.

**Comment by chiffa** [comment] 2016-02-20 22:59
https://github.com/chiffa/BioFlow => follow the instructions to set up the databases, then build the matrix for humans. by that time I will provide you with gists to execute to reproduce the analysis pipeline I am currently running.

**Comment by anntzer** [comment] 2016-02-20 23:24
This is... big.  Any chance you can run the workflow while hooking calls to cholmod to save the matrices (say, as pickles) as they are analyzed and put them on Dropbox?

**Comment by chiffa** [comment] 2016-02-21 00:15
Sure. I'll extract a couple of them for you tomorrow.

**Comment by chiffa** [comment] 2016-02-21 21:02
You can find the matrix dumped here: https://www.dropbox.com/s/ydwcbbghz7u4b12/debug_for_cholesky.dmp?dl=0 I re-installed the 0.2 version and am currently running the same pipeline to see how the machine will perform. I will report tomorrow. I apply Cholesky to that matrix with a fudge of 1e-10

Best,

**Comment by anntzer** [comment] 2016-02-21 22:13
0.2 and pre-0.3 seem to perform the same for me for the cholesky step:
```
In [6]: %time sksparse.cholmod.cholesky(m, 1e-10)
CPU times: user 2.58 s, sys: 1.14 s, total: 3.72 s
Wall time: 1.11 s
Out[6]: <sksparse.cholmod.Factor at 0x7fdfbf1be690>

In [7]: %time scikits.sparse.cholmod.cholesky(m, 1e-10)
CPU times: user 2.52 s, sys: 1.28 s, total: 3.79 s
Wall time: 1.12 s
Out[7]: <scikits.sparse.cholmod.Factor at 0x7fdfbf1be4d0>
```
However, I guess you should also give me the RHS so that I actually solve the system.

**Comment by chiffa** [comment] 2016-02-22 15:18
If finished verifying the performanice issue on my side: it seems that it is due to the machine and not Cholesky decomposition. I did however see a pretty significant RAM performance and a probable leakage closing (RAM usage after a night of execution was 2x lower in the pre-0.3 branch compared to the 0.2).

I will go ahead and install the pre-0.3 on all my machines, thank you very much for the patch!

**Comment by chiffa** [comment] 2016-02-22 23:00
After some examination the main reason for the performance drop was due to the fact that I was comparing processors that were spread by about 6 years in architecture launch dates and that in the meantime linear algebra and threading implementation seem to have made quite a lot of progress.

**Comment by anntzer** [comment] 2016-02-25 20:00
scikit-sparse 0.3 has been released on PyPI.  And there was a great joy etc. (but please check that I haven't messed up something as that's my first release on PyPI ever)
I'll probably leave the old scikits.sparse as it is for now (modulo a small note regarding its deprecation).

**Comment by chiffa** [comment] 2016-02-25 20:02
Good job, thanks for your contribution!

**Closed** 2016-05-20 07:30 UTC
